#!/bin/bash
sudo apt install python3-django -y
sudo apt install python3-pip -y
sudo apt install python3-virtualenv -y
sudo apt install nodejs -y
sudo apt install npm -y
npm install react@18.2.0
npm install react-router-dom@5.3.0
